version: '3.8'

services:
  redis:
    container_name: redis-auth
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379'
    volumes:
      - redis-auth:/data
  db:
    container_name: postgres-auth
    image: postgres:13
    volumes:
      - postgres_auth:/var/lib/postgresql/data/
    ports:
      - '5432'
    env_file:
      - .env.prod
    depends_on:
      - redis
  web:
    build: .
    container_name: auth-api
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env.prod
    depends_on:
      - db
  grpc:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    container_name: auth-grpc
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env.prod
    depends_on:
      - web
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - "50051:50051"
    depends_on:
      - grpc

  jaeger:
      image: jaegertracing/all-in-one:latest
      ports:
      - "6831:6831"
      - "16686:16686"

volumes:
  redis-auth:
    name: redis-auth
  postgres_auth:
    name: postgres_auth
