version: '3.8'

services:
  redis:
    container_name: redis-auth
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379'
    volumes:
      - redis-auth:/data
  db:
    container_name: postgres-auth
    image: postgres:13
    volumes:
      - postgres_auth:/var/lib/postgresql/data/
    ports:
      - '5432'
    env_file:
      - .env.prod
    depends_on:
      - redis
  web:
    build: .
    container_name: auth-api
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - '8000:80'
    depends_on:
      - web

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "5775:5775/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411


volumes:
  redis-auth:
    name: redis-auth
  postgres_auth:
    name: postgres_auth
