FROM python:3.10-slim-buster

WORKDIR /usr/src/app

EXPOSE 50051

COPY ./requirements.txt requirements.txt

COPY ./src ./src

RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./src/grpc_server/protos/auth.proto

ENTRYPOINT ["/bin/sh", "-c" , "python -m src.grpc_server.run"]
