# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0fgateway_backend\"/\n\nPermission\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\npermission\x18\x02 \x01(\t\"%\n\x0bIsPermitted\x12\x16\n\x0ehas_permission\x18\x01 \x01(\x08\"#\n\x04Role\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"\x1f\n\x0bRoleGranted\x12\x10\n\x08has_role\x18\x01 \x01(\x08\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"\x1b\n\x07IsValid\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32\xda\x01\n\x04\x41uth\x12L\n\rHasPermission\x12\x1b.gateway_backend.Permission\x1a\x1c.gateway_backend.IsPermitted\"\x00\x12@\n\x07HasRole\x12\x15.gateway_backend.Role\x1a\x1c.gateway_backend.RoleGranted\"\x00\x12\x42\n\x0cIsAuthorized\x12\x16.gateway_backend.Token\x1a\x18.gateway_backend.IsValid\"\x00\x62\x06proto3')



_PERMISSION = DESCRIPTOR.message_types_by_name['Permission']
_ISPERMITTED = DESCRIPTOR.message_types_by_name['IsPermitted']
_ROLE = DESCRIPTOR.message_types_by_name['Role']
_ROLEGRANTED = DESCRIPTOR.message_types_by_name['RoleGranted']
_TOKEN = DESCRIPTOR.message_types_by_name['Token']
_ISVALID = DESCRIPTOR.message_types_by_name['IsValid']
Permission = _reflection.GeneratedProtocolMessageType('Permission', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSION,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.Permission)
  })
_sym_db.RegisterMessage(Permission)

IsPermitted = _reflection.GeneratedProtocolMessageType('IsPermitted', (_message.Message,), {
  'DESCRIPTOR' : _ISPERMITTED,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.IsPermitted)
  })
_sym_db.RegisterMessage(IsPermitted)

Role = _reflection.GeneratedProtocolMessageType('Role', (_message.Message,), {
  'DESCRIPTOR' : _ROLE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.Role)
  })
_sym_db.RegisterMessage(Role)

RoleGranted = _reflection.GeneratedProtocolMessageType('RoleGranted', (_message.Message,), {
  'DESCRIPTOR' : _ROLEGRANTED,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.RoleGranted)
  })
_sym_db.RegisterMessage(RoleGranted)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.Token)
  })
_sym_db.RegisterMessage(Token)

IsValid = _reflection.GeneratedProtocolMessageType('IsValid', (_message.Message,), {
  'DESCRIPTOR' : _ISVALID,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.IsValid)
  })
_sym_db.RegisterMessage(IsValid)

_AUTH = DESCRIPTOR.services_by_name['Auth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERMISSION._serialized_start=31
  _PERMISSION._serialized_end=78
  _ISPERMITTED._serialized_start=80
  _ISPERMITTED._serialized_end=117
  _ROLE._serialized_start=119
  _ROLE._serialized_end=154
  _ROLEGRANTED._serialized_start=156
  _ROLEGRANTED._serialized_end=187
  _TOKEN._serialized_start=189
  _TOKEN._serialized_end=211
  _ISVALID._serialized_start=213
  _ISVALID._serialized_end=240
  _AUTH._serialized_start=243
  _AUTH._serialized_end=461
# @@protoc_insertion_point(module_scope)
