# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0fgateway_backend\"\"\n\x0bPermissions\x12\x13\n\x0bpermissions\x18\x01 \x03(\t\"\x16\n\x05Roles\x12\r\n\x05roles\x18\x01 \x03(\t\"\x16\n\x05Token\x12\r\n\x05token\x18\x01 \x01(\t\"\x1b\n\x07IsValid\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32\xd2\x01\n\x04\x41uth\x12H\n\x0eGetPermissions\x12\x16.gateway_backend.Token\x1a\x1c.gateway_backend.Permissions\"\x00\x12<\n\x08GetRoles\x12\x16.gateway_backend.Token\x1a\x16.gateway_backend.Roles\"\x00\x12\x42\n\x0cIsAuthorized\x12\x16.gateway_backend.Token\x1a\x18.gateway_backend.IsValid\"\x00\x62\x06proto3')



_PERMISSIONS = DESCRIPTOR.message_types_by_name['Permissions']
_ROLES = DESCRIPTOR.message_types_by_name['Roles']
_TOKEN = DESCRIPTOR.message_types_by_name['Token']
_ISVALID = DESCRIPTOR.message_types_by_name['IsValid']
Permissions = _reflection.GeneratedProtocolMessageType('Permissions', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSIONS,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.Permissions)
  })
_sym_db.RegisterMessage(Permissions)

Roles = _reflection.GeneratedProtocolMessageType('Roles', (_message.Message,), {
  'DESCRIPTOR' : _ROLES,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.Roles)
  })
_sym_db.RegisterMessage(Roles)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.Token)
  })
_sym_db.RegisterMessage(Token)

IsValid = _reflection.GeneratedProtocolMessageType('IsValid', (_message.Message,), {
  'DESCRIPTOR' : _ISVALID,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:gateway_backend.IsValid)
  })
_sym_db.RegisterMessage(IsValid)

_AUTH = DESCRIPTOR.services_by_name['Auth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERMISSIONS._serialized_start=31
  _PERMISSIONS._serialized_end=65
  _ROLES._serialized_start=67
  _ROLES._serialized_end=89
  _TOKEN._serialized_start=91
  _TOKEN._serialized_end=113
  _ISVALID._serialized_start=115
  _ISVALID._serialized_end=142
  _AUTH._serialized_start=145
  _AUTH._serialized_end=355
# @@protoc_insertion_point(module_scope)
