"""empty message

Revision ID: 4c60cfe8e0c4
Revises: d7e3902ce748
Create Date: 2022-05-11 10:07:27.045532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c60cfe8e0c4'
down_revision = 'd7e3902ce748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_history', ['id', 'device_type'])
    op.create_unique_constraint(None, 'permission', ['id'])
    op.create_unique_constraint(None, 'profile', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'totp', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'totp', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_constraint(None, 'permission', type_='unique')
    op.drop_constraint(None, 'auth_history', type_='unique')
    # ### end Alembic commands ###
