"""Initial migration.

Revision ID: b56866ec4608
Revises: 
Create Date: 2022-05-12 13:19:51.336972

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b56866ec4608'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_history', sa.Column('device_type', sa.String(length=10), nullable=False))
    op.add_column('auth_history', sa.Column('ip_address', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'auth_history', ['id', 'device_type'])
    op.create_unique_constraint(None, 'permission', ['id'])
    op.create_unique_constraint(None, 'profile', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.drop_constraint('social_account_user_id_key', 'social_account', type_='unique')
    op.create_unique_constraint(None, 'totp', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'totp', type_='unique')
    op.create_unique_constraint('social_account_user_id_key', 'social_account', ['user_id'])
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_constraint(None, 'permission', type_='unique')
    op.drop_constraint(None, 'auth_history', type_='unique')
    op.drop_column('auth_history', 'ip_address')
    op.drop_column('auth_history', 'device_type')
    # ### end Alembic commands ###
